CREATE USER spring WITH ENCRYPTED PASSWORD 'spring';
CREATE DATABASE securitydb OWNER spring;

INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');